In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import pyarrow.parquet as pq
import pyarrow as pa

# Assuming df is your original DataFrame
filepath = "./data/catB_train.parquet"
df = pd.read_parquet(filepath)

# Splitting the DataFrame into 70% train and 30% test
train_df, test_df = train_test_split(df, test_size=0.3, random_state=42)

# Exporting train and test DataFrames to parquet files
train_filepath = "./data/train_data.parquet"
test_filepath = "./data/test_data.parquet"

# Writing DataFrames to parquet files
train_table = pa.Table.from_pandas(train_df)
test_table = pa.Table.from_pandas(test_df)

pq.write_table(train_table, train_filepath)
pq.write_table(test_table, test_filepath)

In [3]:
train_df

,clntnum,race_desc,ctrycode_desc,clttype,stat_flag,min_occ_date,cltdob_fix,cltsex_fix,flg_substandard,flg_is_borderline_standard,...,recency_giclaim,giclaim_cnt_success,recency_giclaim_success,giclaim_cnt_unsuccess,recency_giclaim_unsuccess,flg_gi_claim_29d435_ever,flg_gi_claim_058815_ever,flg_gi_claim_42e115_ever,flg_gi_claim_856320_ever,f_purchase_lh
8523,956f1fe914,Others,Singapore,P,ACTIVE,2020-08-21,1992-04-19,Male,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
11964,c3509f0aef,Chinese,Singapore,P,ACTIVE,1990-03-20,1948-12-16,Male,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
6554,1cba87acdc,Malay,Singapore,P,ACTIVE,2020-11-24,1988-08-07,Female,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
11395,f2156cdae2,Chinese,Singapore,P,ACTIVE,2008-05-28,1964-06-07,Male,1.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
9632,137fc86021,Malay,Singapore,P,ACTIVE,2019-11-11,1991-11-12,Male,1.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7322,b336ba98b9,Chinese,Singapore,P,ACTIVE,2016-10-01,1996-12-09,Male,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
15804,f142e17df1,None,Singapore,G,ACTIVE,2023-01-01,1992-12-26,Male,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
10853,536ef40e41,Chinese,Singapore,P,ACTIVE,2018-08-07,1987-07-21,Female,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
2255,10e66323a7,Chinese,Singapore,P,ACTIVE,2013-08-26,1986-10-19,Male,1.0,0.0,...,NaN,None,None,None,None,None,None,None,None,1.0
12693,0c3b41e2ec,Chinese,Singapore,P,ACTIVE,2011-02-01,1990-09-11,Male,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN

In [4]:
test_df

,clntnum,race_desc,ctrycode_desc,clttype,stat_flag,min_occ_date,cltdob_fix,cltsex_fix,flg_substandard,flg_is_borderline_standard,...,recency_giclaim,giclaim_cnt_success,recency_giclaim_success,giclaim_cnt_unsuccess,recency_giclaim_unsuccess,flg_gi_claim_29d435_ever,flg_gi_claim_058815_ever,flg_gi_claim_42e115_ever,flg_gi_claim_856320_ever,f_purchase_lh
2397,0d5be727a5,None,Singapore,G,ACTIVE,2022-04-01,1985-08-24,Male,NaN,NaN,...,NaN,None,None,None,None,None,None,None,None,NaN
19035,ba6304f60f,None,Singapore,G,ACTIVE,2023-01-01,1995-04-15,Male,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
19957,e14e8efecb,Chinese,Singapore,P,ACTIVE,2018-11-07,1985-11-08,Female,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,1.0
16719,d060e9c0bb,Chinese,Taiwan (R.O.C),P,ACTIVE,2015-06-04,1964-11-21,Female,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
234,d80d67ce49,None,Singapore,G,ACTIVE,2021-11-01,1989-03-06,Female,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15202,28925139d5,None,Singapore,G,ACTIVE,2013-08-01,1992-01-18,Male,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
11661,c904e08664,Chinese,Singapore,P,ACTIVE,2011-09-08,1975-01-03,Female,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
12412,e0b82f0066,Chinese,Singapore,P,ACTIVE,2003-04-14,1972-05-05,Female,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
3942,748ba90d99,Chinese,Singapore,P,LAPSED,2019-03-31,1979-03-08,Female,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN
17906,3a3748f081,Chinese,Singapore,P,ACTIVE,2008-02-01,1975-11-27,Female,0.0,0.0,...,NaN,None,None,None,None,None,None,None,None,NaN